# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 332d5db2acaa9cacb6b4ce61bd98eac089f9d4d19665771f8cbab7a41dfb251750fe2345f0760029f077c727012300016789a3d1006aa676ba9e391bcf61634a

test:
  secret_key_base: 6a4f928149f3910c40e9ad05fec6b2778b58aa25b6d116880dfc16a324db3af6ad211379741a1723446be0b155ee51b23e575f17393ec1b5368ccb6736ea092d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
